### ISSUE TITLE
Title Screen Rendering Glitch

### ISSUE THREAD

**Issue by apowers313** [guillaumebrunerie/nethackweb#1]
This is beautiful. I love how you made the menus "clickable" too. Great work.

On an 11" iPad Pro 2024 in the Safari browser (iOS 18.x) the title screen has a slight rendering glitch.

<img width="1210" alt="image" src="https://github.com/user-attachments/assets/702a6a47-3cfc-4fb5-9b86-a17c77c61e28">

**Comment by guillaumebrunerie** [comment]
Not sure why this happens (and I can’t reproduce it in Chrome or on Android), but I've now reimplemented the positioning of the copyright message in a slightly more straightforward way, so hopefully it fixes this rendering issue.

**Comment by apowers313** [comment]
Looks great now, thanks!

<img width="1210" alt="image" src="https://github.com/user-attachments/assets/79cec338-f78b-4c59-ad0b-460ee902ea56">
